import {describe,expect,it} from "vitest";
import {Simulation} from "../src/simulation/core/simulation";
describe("simulation kernel",()=>{
 it("starts with exactly two immortal founders",()=>{const s=new Simulation(1);expect(s.livingCitizens).toHaveLength(2);expect(Object.values(s.state.citizens).every(c=>c.founder)).toBe(true);});
 it("is deterministic for the same seed",()=>{const a=new Simulation(42),b=new Simulation(42);a.createChild(a.state.citizens.c_king,a.state.citizens.c_queen);b.createChild(b.state.citizens.c_king,b.state.citizens.c_queen);expect(a.state).toEqual(b.state);});
 it("supports marriage, siblings, ancestors, and descendants",()=>{const s=new Simulation(4);const king=s.state.citizens.c_king,queen=s.state.citizens.c_queen;s.marry(king,queen);const first=s.createChild(king,queen),second=s.createChild(king,queen);expect(king.spouseId).toBe(queen.id);expect(queen.spouseId).toBe(king.id);expect(first.parentIds).toEqual([king.id,queen.id]);expect(king.childIds).toEqual([first.id,second.id]);expect(queen.childIds).toEqual([first.id,second.id]);expect(s.getSiblings(first).map(c=>c.id)).toEqual([second.id]);expect(s.getAncestors(first).map(c=>c.id)).toEqual([king.id,queen.id]);expect(s.getDescendants(king).map(c=>c.id)).toEqual([first.id,second.id]);});

 it("rejects invalid marriages",()=>{const s=new Simulation(5);const king=s.state.citizens.c_king,queen=s.state.citizens.c_queen;s.marry(king,queen);expect(()=>s.marry(king,queen)).toThrow();});

 it("keeps founders immortal while descendants age and can die",()=>{const s=new Simulation(2);const c=s.createChild(s.state.citizens.c_king,s.state.citizens.c_queen);c.genome.longevity=1;s.advance(2);expect(s.state.citizens.c_king.deathTick).toBeUndefined();expect(s.state.citizens.c_queen.deathTick).toBeUndefined();expect(c.deathTick).toBeDefined();});
 it("allows genetic technology only on founders and propagates its provenance",()=>{const s=new Simulation(3);const tech={id:"longevity-1",name:"Enhanced Longevity",description:"",cost:10,mode:"activeFounder" as const,prerequisiteIds:[]};s.applyFounderGeneticTech(s.state.citizens.c_king.id,tech);const c=s.createChild(s.state.citizens.c_king,s.state.citizens.c_queen);expect(()=>s.applyFounderGeneticTech(c.id,tech)).toThrow();expect(c.genome.geneticTechIds).toContain("longevity-1");expect(c.royalGeneticHeritage).toBe(true);});
});